---
engines:
  duplication:
    enabled: true
  config:
    languages:
    - php
  fixme:
    enabled: true
  phpmd:
    enabled: true
    checks:
      CleanCode/BooleanArgumentFlag:
        enabled: false
      Identical code:
        enabled: false
ratings:
  paths:
  - "**.php"
exclude_paths:
- tests/
