engines:
  duplication:
    enabled: false
    config:
      languages:
      - php
ratings:
  paths:
  - "**.php"
exclude_paths:
- tests/
- "src/DeathByCaptcha/SocketClient.php"
- "src/DeathByCaptcha/HttpClient.php"
